#!/usr/bin/env python3

from futhark_ffi import Futhark
import numpy as np

import _test


def main():
    test = Futhark(_test)
    res = test.test3(np.arange(10))
    test.from_futhark(res)


if __name__ == "__main__":
    main()
